### ISSUE TITLE
License

### ISSUE THREAD

**Issue by walkjivefly** [BatuhanUsluel/ArbitrageBot#5]
What license is this code released under?

**Comment by MrBobBarker** [comment]
There are only two contributors, myself and BatuhanUsluel. I consider all my contributions to be under MIT. If BatuhanUsluel agrees the MIT license should be officially added to the repo.

Note that the API libraries are of unknown license.

**Comment by BatuhanUsluel** [comment]
Added MIT license
73a7aad4585ca5b2fdb174fca6014bb687fb60a8
