### ISSUE TITLE
Error message when running

### ISSUE THREAD

**Issue by colwinlabs** [BatuhanUsluel/ArbitrageBot#6]
When I run the bot it leaves the following message, already configure the keys of Poloniex and Bittrex.

ERROR -  01 Failed to Query Poloniex for Balance Data, Restarting Loop

**Comment by BatuhanUsluel** [comment]
Fixed bittrex and poloniex api using wrong key/secrets a0e359f93f65cb3298a04d7aea222bc9e6a91228.  Replaced bittrex.py with older version fb9ec70b5bbe36d290116a17dc99b8c6ea0d9129. That should fix the problem.

**Comment by colwinlabs** [comment]
Thanks for replying, download the new version, configure it and the following message is displayed:
![bot](https://user-images.githubusercontent.com/30303805/30252280-0bc43744-9635-11e7-8cb2-10c9f53545e0.png)

**Comment by BatuhanUsluel** [comment]
I couldn't recreate the error, but I did manage to find a few other people experiencing the same problem when I searched it up. Most of them recommend creating a new API key(poloniex). Here is an explanation someone has posted:

>  "The 422 (Unprocessable Entity) status code is directly reported by Poloniex server. It means the server understands the content type of the request entity, and the syntax of the request entity is correct, but was unable to process the contained instructions.
> 
> Nevertheless, I'm not sure why Poloniex returns error 422 or what is wrong with old APY keys."

You might also want to update to version 54e005e1c2d45de0e8fd4fae418e91a0e66b77da(removed the unneccary print msgs used while testing)

**Comment by kingchenc** [comment]
i get this error :o 

![unbenannt](https://user-images.githubusercontent.com/14137153/30333542-75cbad94-97dd-11e7-8a4c-47adf635d58e.png)

**Comment by kingchenc** [comment]
first error ->

=============== RESTART: C:\Bots\ArbitrageBot-master\arbbot.py ===============
Traceback (most recent call last):
  File "C:\Bots\ArbitrageBot-master\arbbot.py", line 9, in <module>
    from bittrex import bittrex
  File "C:\Bots\ArbitrageBot-master\bittrex.py", line 109
    return self.query('getdeposithistory', {'currency': currency, 'count': count})
                                                                                 ^
TabError: inconsistent use of tabs and spaces in indentation

deleted the tab, and create spaces, then another problem :P 

=============== RESTART: C:\Bots\ArbitrageBot-master\arbbot.py ===============
Traceback (most recent call last):
  File "C:\Bots\ArbitrageBot-master\arbbot.py", line 9, in <module>
    from bittrex import bittrex
  File "C:\Bots\ArbitrageBot-master\bittrex.py", line 3, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

i know, python 3 urllib2 was merged into urllib... 
import urllib.request this fixx the error, or import urllib.request as urllib2, but that give that @ThreadStarter Error ->

2017-09-12 19:12:43,209 - ERROR - Failed to Query Bittrex API, Restarting Loop

**Comment by MrBobBarker** [comment]
This reversion breaks the breaks the changes to ensure Python2/Python3 compatibility. Note that python3 is more strict about tab/space mixing as well as the urllib stuff. Without the exception handling the script won't work.

As for the API error message, I haven't done live testing of this script. I've been distracted by other projects but I do plan to live test the script in the future.

**Comment by kingchenc** [comment]
Allright thank you, now with python 2.7 the "script" work fine without any error,
edit: works fine with the fixes a0e359f and fb9ec70 @BatuhanUsluel
